//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<int> IdPosition { get; set; }
    
        public virtual Positions Positions { get; set; }
    }
}
